import type { SettingConfig } from '~~/shared/types/settings'
import i18nOptions from '~~/i18n/i18n.options'

// 存储提供商的枚举值
export const STORAGE_PROVIDERS = ['local', 's3', 'openlist'] as const
export type StorageProvider = (typeof STORAGE_PROVIDERS)[number]

export const DEFAULT_SETTINGS = [
  // NAMESPACE: system
  {
    namespace: 'system',
    key: 'firstLaunch',
    type: 'boolean',
    value: true,
    defaultValue: true,
    label: 'settings.system.firstLaunch.label',
    description: 'settings.system.firstLaunch.description',
    isReadonly: true,
  },
  // NAMESPACE: app
  {
    namespace: 'app',
    key: 'title',
    type: 'string',
    defaultValue: 'ChronoFrame',
    label: 'settings.app.title.label',
    description: 'settings.app.title.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'slogan',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.slogan.label',
    description: 'settings.app.slogan.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'author',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.author.label',
    description: 'settings.app.author.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'avatarUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.avatarUrl.label',
    description: 'settings.app.avatarUrl.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.theme',
    type: 'string',
    defaultValue: 'dark',
    enum: ['light', 'dark', 'system'],
    label: 'settings.app.appearance.theme.label',
    description: 'settings.app.appearance.theme.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.themeToggle',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.app.appearance.themeToggle.label',
    description: 'settings.app.appearance.themeToggle.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.cardCornerRadius',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.app.appearance.cardCornerRadius.label',
    description: 'settings.app.appearance.cardCornerRadius.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.cardCornerRadiusValue',
    type: 'number',
    defaultValue: 12,
    label: 'settings.app.appearance.cardCornerRadiusValue.label',
    description: 'settings.app.appearance.cardCornerRadiusValue.description',
    isPublic: true,
  },
  // 站点对外访问的规范地址（用于 OG 分享图/分享链接）。留空则跟随当前访问域名；
  // 内网/IP 部署、或希望分享链接固定到某个域名时在此填写，如 https://dev.1xc.top
  {
    namespace: 'app',
    key: 'siteUrl',
    type: 'string',
    defaultValue: process.env.NUXT_PUBLIC_SITE_URL || '',
    label: 'settings.app.siteUrl.label',
    description: 'settings.app.siteUrl.description',
    isPublic: true,
  },
  // 允许访问的主机白名单（Host 头），逗号分隔，可填域名或内网 IP；
  // 配置 `*` 表示允许任意来源（内网/多域名/反代场景常用）。
  // 服务启动时生效，修改后需重启；对应启动环境变量 NUXT_ALLOWED_HOSTS
  {
    namespace: 'app',
    key: 'allowedHosts',
    type: 'string',
    defaultValue: process.env.NUXT_ALLOWED_HOSTS || '',
    label: 'settings.app.allowedHosts.label',
    description: 'settings.app.allowedHosts.description',
    isPublic: true,
  },
  // 回收站保留策略：移入回收站的照片在「多少天」后自动彻底删除；never=永不自动删除
  {
    namespace: 'app',
    key: 'trash.retention',
    type: 'string',
    defaultValue: '30',
    enum: ['never', '7', '14', '30', '60', '90', '180', '365'],
    label: 'settings.app.trash.retention.label',
    description: 'settings.app.trash.retention.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'loader.images',
    type: 'json',
    value: ['/loader/mountains_sm.jpg', '/loader/meadow_sm.jpg', '/loader/sea_sm.jpg'],
    defaultValue: ['/loader/mountains_sm.jpg', '/loader/meadow_sm.jpg', '/loader/sea_sm.jpg'],
    label: 'settings.app.loader.images.label',
    description: 'settings.app.loader.images.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'loader.cardStyle',
    type: 'string',
    defaultValue: 'liquid',
    enum: ['liquid', 'skeuo'],
    label: 'settings.app.loader.cardStyle.label',
    description: 'settings.app.loader.cardStyle.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'loader.animation',
    type: 'string',
    defaultValue: 'stack',
    enum: ['stack', 'fan'],
    label: 'settings.app.loader.animation.label',
    description: 'settings.app.loader.animation.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.maxFileSize',
    type: 'number',
    defaultValue: 256,
    label: 'settings.app.upload.maxFileSize.label',
    description: 'settings.app.upload.maxFileSize.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.duplicateCheck.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.system.upload.duplicateCheck.enabled.label',
    description: 'settings.system.upload.duplicateCheck.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.duplicateCheck.mode',
    type: 'string',
    defaultValue: 'skip',
    enum: ['warn', 'block', 'skip'],
    label: 'settings.system.upload.duplicateCheck.mode.label',
    description: 'settings.system.upload.duplicateCheck.mode.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'webglImageViewerDebug',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.webglImageViewerDebug.label',
    description: 'settings.system.webglImageViewerDebug.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.github.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.auth.github.enabled.label',
    description: 'settings.system.auth.github.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.github.clientId',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.github.clientId.label',
    description: 'settings.system.auth.github.clientId.description',
  },
  {
    namespace: 'system',
    key: 'auth.github.clientSecret',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.github.clientSecret.label',
    description: 'settings.system.auth.github.clientSecret.description',
    isSecret: true,
  },
  // NAMESPACE: privacy
  {
    namespace: 'privacy',
    key: 'upload.autoEraseLocation',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.privacy.upload.autoEraseLocation.label',
    description: 'settings.privacy.upload.autoEraseLocation.description',
    isPublic: true,
  },
  // NAMESPACE: map
  {
    namespace: 'map',
    key: 'provider',
    type: 'string',
    defaultValue: 'maplibre',
    enum: ['mapbox', 'maplibre'],
    label: 'settings.map.provider.label',
    description: 'settings.map.provider.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.token.label',
    description: 'settings.map.mapbox.token.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.style',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.style.label',
    description: 'settings.map.mapbox.style.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.token.label',
    description: 'settings.map.maplibre.token.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.style',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.style.label',
    description: 'settings.map.maplibre.style.description',
    isPublic: true,
  },
  // NAMESPACE: location
  {
    namespace: 'location',
    key: 'language',
    type: 'string',
    defaultValue: 'en',
    enum: i18nOptions.locales.map(({ language }) => language),
    label: 'settings.location.language.label',
    description: 'settings.location.language.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.mapbox.token.label',
    description: 'settings.location.mapbox.token.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'nominatim.baseUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.nominatim.baseUrl.label',
    description: 'settings.location.nominatim.baseUrl.description',
    isPublic: true,
  },
  // NAMESPACE: storage
  {
    namespace: 'storage',
    key: 'provider',
    type: 'number',
    defaultValue: null,
    label: 'settings.storage_provider.provider.label',
    description: 'settings.storage_provider.provider.description',
  },
  // NAMESPACE: analytics
  {
    namespace: 'analytics',
    key: 'headScripts',
    type: 'string',
    defaultValue: '',
    label: 'settings.analytics.headScripts.label',
    description: 'settings.analytics.headScripts.description',
    isPublic: true,
  },
  {
    namespace: 'analytics',
    key: 'bodyScripts',
    type: 'string',
    defaultValue: '',
    label: 'settings.analytics.bodyScripts.label',
    description: 'settings.analytics.bodyScripts.description',
    isPublic: true,
  },
] as const satisfies SettingConfig[]

export const settingNamespaces = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.namespace)),
] as const
export const settingKeys = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.key)),
] as const

export type SettingNamespace = (typeof settingNamespaces)[number]
export type SettingKey<N extends SettingNamespace> = Extract<
  (typeof DEFAULT_SETTINGS)[number],
  { namespace: N }
>['key']
